#!/bin/bash

SPARK_CONF_DIR=$SPARK_CONF_DIR
SPARK_LOG_DIR=$SPARK_LOG_DIR
SPARK_MASTER_HOST=maquina_master
SPARK_MASTER_PORT=7077
SPARK_MASTER_WEBUI_PORT=9090
SPARK_WORKER_CORES=18
SPARK_WORKER_MEMORY=50g
